#!/bin/sh 

case $1 in
    clean)
        dune clean --build-dir /tmp/build --profile release
        ;;
    pack)
        bin_name=$2
        bin_dir=/tmp/build/default/bin
        bin=$bin_dir/$bin_name.exe
        [ -f $bin ] || exit 10
        pack_dir=/tmp/$bin_name
        chmod +rwx $bin
        strip $bin
        if [ -d $pack_dir ]; then
            rm $pack_dir/*
        else 
            mkdir $pack_dir
        fi
        bin_new=$pack_dir/$bin_name.$(arch)
        cp $bin $bin_new
        sha256sum $bin_new > $bin_new.sha256
        tar -czf $bin_new.tar.gz -C $pack_dir $bin_name.$(arch) 
        echo "packages exported to $pack_dir"
        ;;
    *)
        dune build --build-dir /tmp/build --profile release
        ls -l /tmp/build/default/bin
        ;;
esac
